---
kind: pipeline
name: default

clone:
  disable: true

steps:
- name: clone
  image: docker:git
  commands:
  - git clone https://github.com/thinkjs/www.thinkjs.org.git

- name: submodules_push
  image: lizheming/drone-submodules-push
  settings:
    branch: master
    remote: git@github.com:thinkjs/www.thinkjs.org.git
    path: /tmp
    commit_message: "submodule trigger auto-update"
    ssh_key:
      from_secret: GIT_PUSH_SSH_KEY


